spring: 
  application: 
    name: movie-catalog-service
management: 
  endpoints: 
    web: 
      base-path: /actuator
      exposure:
        include: health,info,refresh
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka